#!/bin/bash

echo "=== CUSTOM DOMAIN SETUP FOR SRICHAKRA ==="
echo "Setting up srichakraacademy.org domain..."
echo ""

echo "🌐 CUSTOM DOMAIN CONFIGURATION STEPS:"
echo ""

echo "1. 📋 CURRENT STATUS:"
echo "   ✅ Firebase project: srichakraacademy-3f745"
echo "   ✅ Default URL: https://srichakraacademy-3f745.web.app"
echo "   🎯 Target URL: https://srichakraacademy.org"
echo ""

echo "2. 🔧 FIREBASE CONSOLE STEPS:"
echo "   Visit: https://console.firebase.google.com/project/srichakraacademy-3f745/hosting/main"
echo "   a) Click 'Add custom domain'"
echo "   b) Enter: srichakraacademy.org"
echo "   c) Follow the domain verification steps"
echo "   d) Update DNS records as instructed"
echo ""

echo "3. 📝 DNS CONFIGURATION REQUIRED:"
echo "   You'll need to add these DNS records to your domain registrar:"
echo "   Type: A"
echo "   Name: @"
echo "   Value: (Firebase will provide IP addresses)"
echo ""
echo "   Type: A"
echo "   Name: www"
echo "   Value: (Firebase will provide IP addresses)"
echo ""

echo "4. 🚀 DEPLOYMENT COMMAND:"
echo "   After DNS is configured, deploy with:"
echo "   firebase deploy --only hosting"
echo ""

echo "5. ⏱️ PROPAGATION TIME:"
echo "   DNS changes can take 24-48 hours to propagate"
echo "   SSL certificate will be automatically provisioned"
echo ""

echo "📋 ALTERNATIVE QUICK SETUP:"
echo "If your domain is already working, you might need to:"
echo "1. Point your domain's DNS to Firebase IP addresses"
echo "2. Or use your existing hosting with Firebase build files"
echo ""

echo "🔗 MANUAL STEPS IN FIREBASE CONSOLE:"
echo "1. Go to: https://console.firebase.google.com/project/srichakraacademy-3f745/hosting/main"
echo "2. Click 'Add custom domain'"
echo "3. Enter 'srichakraacademy.org'"
echo "4. Complete verification process"
echo "5. Update DNS as instructed"
echo ""

echo "📱 CURRENT WORKING URLS:"
echo "• Firebase Default: https://srichakraacademy-3f745.web.app"
echo "• Admin Login: https://srichakraacademy-3f745.web.app/admin/login"
echo ""
echo "📱 AFTER CUSTOM DOMAIN SETUP:"
echo "• Custom Domain: https://srichakraacademy.org"
echo "• Admin Login: https://srichakraacademy.org/admin/login"
echo ""

echo "✨ READY TO CONFIGURE CUSTOM DOMAIN! ✨"
echo "Visit Firebase Console to complete the setup."
