#!/bin/bash

echo "=== DEPLOY TO EXISTING SERVER GUIDE ==="
echo "How to use your built files on srichakraacademy.org"
echo ""

echo "📁 BUILT FILES LOCATION:"
echo "Your compiled application is in:"
echo "/Volumes/t7 sharma/vs coad/all folders from vs code creater /srichakra/dist/public/"
echo ""

echo "📋 FILES TO COPY TO YOUR SERVER:"
echo "Copy all contents from dist/public/ to your web server:"
echo ""
echo "Local Path: ./dist/public/"
echo "Contains:"
echo "├── index.html (main app file)"
echo "├── assets/ (CSS, JS, images)"
echo "│   ├── index-[hash].css"
echo "│   ├── index-[hash].js"
echo "│   └── [image files]"
echo "└── [other static files]"
echo ""

echo "🚀 UPLOAD METHODS:"
echo ""
echo "METHOD 1 - FTP/SFTP:"
echo "• Use FileZilla, WinSCP, or similar"
echo "• Upload dist/public/* to your server's public_html/"
echo "• Ensure index.html is in the root"
echo ""
echo "METHOD 2 - SSH/SCP:"
echo "scp -r ./dist/public/* user@srichakraacademy.org:/path/to/web/root/"
echo ""
echo "METHOD 3 - cPanel File Manager:"
echo "• Log into your hosting cPanel"
echo "• Use File Manager"
echo "• Upload and extract files to public_html/"
echo ""

echo "⚙️ SERVER CONFIGURATION:"
echo ""
echo "Add this to your .htaccess file (for Apache):"
echo "RewriteEngine On"
echo "RewriteCond %{REQUEST_FILENAME} !-f"
echo "RewriteCond %{REQUEST_FILENAME} !-d"
echo "RewriteRule . /index.html [L]"
echo ""
echo "For Nginx, add to your config:"
echo "try_files \$uri \$uri/ /index.html;"
echo ""

echo "🔧 AFTER UPLOAD:"
echo "Your URLs will work as:"
echo "• Main site: https://srichakraacademy.org"
echo "• Admin login: https://srichakraacademy.org/admin/login"
echo "• All features: https://srichakraacademy.org/[any-route]"
echo ""

echo "📱 TESTING:"
echo "1. Upload files to your server"
echo "2. Visit https://srichakraacademy.org"
echo "3. Test admin login with credentials:"
echo "   Email: admin@srichakra.com"
echo "   Password: admin123"
echo ""

echo "💡 BENEFITS OF THIS APPROACH:"
echo "• Use your existing domain immediately"
echo "• No DNS changes required"
echo "• Works with your current hosting"
echo "• Full control over the server"
echo ""

echo "✨ READY TO DEPLOY TO YOUR SERVER! ✨"
