#!/bin/bash

echo "=== Srichakra Database Setup ==="
echo ""
echo "To connect to your Supabase database, you need to:"
echo ""
echo "1. Go to your Supabase dashboard: https://supabase.com/dashboard"
echo "2. Select your project: ugbnpszftpqxrpxabpyh"
echo "3. Go to Settings → Database"
echo "4. Find your database password"
echo ""
echo "5. Update the .env file:"
echo "   Replace 'YOUR_DB_PASSWORD' with your actual password in this line:"
echo "   DATABASE_URL=postgresql://postgres.ugbnpszftpqxrpxabpyh:YOUR_DB_PASSWORD@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
echo ""
echo "6. Then run: npm run db:push"
echo ""
echo "Your Supabase project details:"
echo "- Project Reference: ugbnpszftpqxrpxabpyh"
echo "- Region: ap-south-1 (Asia Pacific - Mumbai)"
echo "- URL: https://ugbnpszftpqxrpxabpyh.supabase.co"
echo ""
echo "After updating the password, the application will have:"
echo "✅ Real database for all users, admins, schools, and students"
echo "✅ Persistent data that survives server restarts"
echo "✅ Proper authentication and session management"
echo "✅ All CRUD operations for schools and students"
